export type SeedItem = {
  name: string;
  description?: string;
  price: number;
};

export type SeedCategory = {
  name: string;
  section: 'food' | 'drinks';
  sortOrder: number;
  items: SeedItem[];
};

// Transcribed from "THE HIDEOUT NIKE LAKE FOOD MENU.docx".
// Items that had no price listed in the source document are set to 0 —
// update them with real prices from the admin dashboard before going live.
export const SEED_CATEGORIES: SeedCategory[] = [
  {
    name: 'Pepper Soup & Traditional Delicacies',
    section: 'food',
    sortOrder: 1,
    items: [
      { name: 'Catfish Pepper Soup', price: 0, description: 'Tender catfish simmered in a fragrant blend of traditional spices, herbs and fresh peppers, served with unripe plantain.' },
      { name: 'Whole Catfish Pepper Soup', price: 0, description: 'A whole catfish delicately cooked in a rich, aromatic pepper soup broth infused with traditional spices and herbs.' },
      { name: 'Isi-Ewu Ndi Hideout', price: 0, description: 'A luxurious take on the classic Igbo delicacy — tender goat head slow-cooked in a rich, spicy palm-oil sauce with traditional aromatics.' },
      { name: 'Abacha — African Salad', price: 0, description: 'Shredded cassava tossed in a traditional palm-oil dressing with garden eggs, utazi, onions and authentic local spices.' },
      { name: 'Achicha', price: 0, description: 'A traditional Eastern Nigerian delicacy made from dried cocoyam granules, prepared with a rich blend of palm oil, spices and local ingredients.' },
      { name: 'Agidi with Oxtail', price: 0, description: 'Soft, silky agidi paired with succulent, slow-cooked oxtail in a deeply flavoured, savoury sauce.' },
      { name: 'Palm Wine', price: 0 },
    ],
  },
  {
    name: 'Rice & Noodle Specialties',
    section: 'food',
    sortOrder: 2,
    items: [
      { name: 'Jambalaya Rice', price: 0, description: 'A vibrant, flavour-packed rice dish cooked with a medley of spices, vegetables and savoury proteins.' },
      { name: 'Ofada Rice', price: 0, description: 'Authentic local Ofada rice served with a rich, spicy sauce, delivering the unmistakable taste of traditional Nigerian cuisine.' },
      { name: 'Native Rice', price: 0, description: 'Aromatic Nigerian-style rice prepared with traditional spices and savoury ingredients for a deeply satisfying local flavour.' },
      { name: 'Pepper Soup Noodles', price: 0, description: 'Noodles infused with the bold, aromatic flavours of Nigerian pepper soup, served with your choice of protein (Goat Meat, Chicken, Turkey or Pork) and sweetcorn.' },
    ],
  },
  {
    name: "Grandma's Signatures",
    section: 'food',
    sortOrder: 3,
    items: [
      { name: 'Grandma Chicken', price: 0, description: "Succulent chicken prepared in a rich, deeply seasoned house recipe inspired by the comforting flavours of Grandma's kitchen." },
      { name: 'Grandma Duck', price: 0, description: 'Tender duck slow-cooked and generously seasoned with our signature house blend for a rich, aromatic and unforgettable experience.' },
    ],
  },
  {
    name: 'Grills & BBQ',
    section: 'food',
    sortOrder: 4,
    items: [
      { name: 'Grilled Tilapia Fish', price: 0, description: 'Fresh tilapia seasoned with our signature spices and grilled to perfection for a smoky, tender finish.' },
      { name: 'Grilled Catfish — BBQ', price: 0, description: 'Juicy catfish marinated in a bold BBQ seasoning, grilled over high heat for a beautifully charred exterior and succulent centre.' },
      { name: 'Smoked Catfish', price: 0, description: 'Fresh catfish traditionally smoked to perfection, delivering a rich, deep smoky flavour.' },
      { name: 'Grilled Grasscutter — Nchi', price: 0, description: 'Tender grasscutter marinated in aromatic spices and grilled for a beautifully smoky, flavour-packed finish.' },
      { name: 'Sweet & Spicy Pork', price: 0, description: 'Succulent cuts of pork glazed in a perfectly balanced sweet-and-spicy sauce, then grilled for a caramelised finish.' },
    ],
  },
  {
    name: 'Snails & Special Delicacies',
    section: 'food',
    sortOrder: 5,
    items: [
      { name: 'Snail with Vegetable Sauce', price: 0, description: 'Tender, perfectly seasoned snails served with a rich and savoury vegetable sauce.' },
      { name: 'Snail with Pepper Sauce', price: 0, description: 'Juicy snails tossed in a fiery, aromatic pepper sauce for lovers of bold Nigerian flavours.' },
    ],
  },
  {
    name: 'Signature Platters',
    section: 'food',
    sortOrder: 6,
    items: [
      { name: 'Mixed Meat Platter', price: 0, description: "A generous selection of assorted grilled meats and house favourites, perfectly seasoned and served for the ultimate meat lover's experience." },
      { name: 'Surf & Turf Platter', price: 0, description: 'A premium combination of succulent grilled meats and perfectly seasoned seafood, bringing land and sea together on one indulgent platter.' },
      { name: 'Seafood Platter', price: 0, description: 'An impressive selection of the finest grilled and seasoned seafood, prepared to highlight their natural flavours and smoky richness.' },
    ],
  },
  {
    name: "Noah's Ark",
    section: 'food',
    sortOrder: 7,
    items: [
      { name: "Noah's Ark (Large)", price: 0 },
      { name: "Noah's Ark (Medium)", price: 0, description: 'Our most extravagant sharing experience — an indulgent feast combining premium grilled meats, succulent poultry and beautifully seasoned seafood, created for the table to share and enjoy.' },
    ],
  },
  {
    name: 'Suya & Open-Fire Grills',
    section: 'food',
    sortOrder: 8,
    items: [
      { name: 'Classic Beef Suya', price: 0, description: 'Thinly sliced, tender beef coated in our signature suya spice blend and grilled over open flames for a smoky, spicy finish.' },
      { name: 'Beef Suya Strips', price: 0, description: 'Succulent strips of premium beef generously seasoned with our signature yaji and char-grilled to perfection.' },
      { name: 'Chicken Suya', price: 0, description: 'Tender chicken pieces marinated in aromatic spices, coated with our signature yaji and grilled until beautifully smoky and golden.' },
      { name: 'Pork Suya', price: 0, description: 'Succulent pork coated in a sweet-and-spicy suya seasoning, grilled until perfectly charred and flavourful.' },
      { name: 'Goat Meat Suya', price: 0, description: 'Tender goat meat seasoned with traditional yaji and flame-grilled for an intensely smoky and savoury bite.' },
      { name: 'Gizzard Suya', price: 0, description: 'Seasoned chicken gizzards grilled over open flames and finished with our signature suya spice for a deliciously smoky, chewy texture.' },
    ],
  },
  {
    name: 'Juices & Non-Alcoholic Refreshments',
    section: 'drinks',
    sortOrder: 1,
    items: [
      { name: 'Chi Exotic', price: 4000, description: 'A tropical fruit blend bursting with refreshing fruity flavours.' },
      { name: 'Cranberry Juice', price: 3000, description: 'A refreshing sweet-tart fruit juice, perfect on its own or as a cocktail mixer.' },
      { name: "Martinelli's Apple Juice", price: 25000, description: 'Premium sparkling apple juice with a crisp, naturally fruity finish.' },
      { name: 'Water', price: 800, description: 'Chilled bottled water.' },
    ],
  },
  {
    name: 'Milkshakes',
    section: 'drinks',
    sortOrder: 2,
    items: [
      { name: 'Strawberry & Cream', price: 12000, description: 'Creamy vanilla milkshake blended with sweet strawberries and finished with a smooth cream topping.' },
      { name: 'Banana Shake', price: 12000, description: 'A rich and creamy banana blend made with ripe bananas and chilled milk.' },
      { name: 'Vanilla & Waffles', price: 12000, description: 'A luxurious vanilla milkshake topped with indulgent waffle goodness.' },
      { name: 'Oreo Delight', price: 12000, description: 'A creamy Oreo-infused milkshake loaded with chocolate-cookie flavour.' },
      { name: 'Snickers Milkshake', price: 12000, description: 'A decadent blend of chocolate, caramel and peanut flavours inspired by the classic Snickers bar.' },
      { name: "Lastdrop's Freak-Chaos Shake", price: 16000, description: 'An outrageous signature milkshake loaded with indulgent toppings, sweet treats and pure dessert chaos.' },
      { name: 'Oreo Avalanche', price: 14000, description: 'A rich Oreo-loaded shake topped with generous cookie goodness for the ultimate chocolate-cookie experience.' },
      { name: 'Midnight Sweet Dreams', price: 14000, description: 'A dark, indulgent chocolate milkshake created for serious sweet-tooth cravings.' },
      { name: 'Caramel Thunder Shake', price: 14000, description: 'A creamy caramel explosion with rich caramel flavour and indulgent toppings.' },
    ],
  },
  {
    name: 'Signature Cocktails',
    section: 'drinks',
    sortOrder: 3,
    items: [
      { name: 'Long Island Iced Tea', price: 10000, description: 'A bold blend of spirits, citrus and cola with a smooth, refreshing finish.' },
      { name: 'Tequila Sunrise', price: 10000, description: 'Tequila, orange juice and grenadine layered into a vibrant, sweet and citrusy classic.' },
      { name: 'Sex on the Beach', price: 10000, description: 'A fruity combination of vodka, peach, orange and cranberry flavours.' },
      { name: 'Blue Hawaii', price: 10000, description: 'A tropical cocktail combining rum, citrus and blue curaçao for a refreshing island-inspired experience.' },
      { name: 'Paradise', price: 10000, description: 'A bright, tropical cocktail with fruity and citrus notes.' },
      { name: 'Margarita', price: 10000, description: 'A refreshing blend of tequila, citrus and orange liqueur with a crisp, tangy finish.' },
      { name: 'Cosmopolitan', price: 10000, description: 'Vodka, cranberry and citrus combined into an elegant, vibrant classic.' },
      { name: 'Piña Colada', price: 10000, description: 'A creamy tropical blend of coconut, pineapple and rum.' },
      { name: 'Strawberry Daiquiri', price: 10000, description: 'A refreshing frozen-style cocktail combining strawberries, rum and citrus.' },
      { name: 'Chapman Cocktail', price: 10000, description: 'A Nigerian favourite blending fruity flavours, citrus, bitters and a refreshing fizzy finish.' },
      { name: 'Russian Kiss', price: 10000, description: 'A smooth, fruity cocktail with a sweet and refreshing finish.' },
    ],
  },
  {
    name: 'Mocktails',
    section: 'drinks',
    sortOrder: 4,
    items: [
      { name: 'Chapman', price: 9000, description: 'A refreshing blend of fruity flavours, citrus, bitters and sparkling fizz.' },
      { name: 'Virgin Sunrise', price: 9000, description: 'A vibrant combination of orange and tropical flavours with a beautiful sunrise effect.' },
      { name: 'Virgin Swimming Pool', price: 9000, description: 'A creamy, tropical and refreshing blend inspired by the classic Swimming Pool cocktail.' },
    ],
  },
  {
    name: 'Shots',
    section: 'drinks',
    sortOrder: 5,
    items: [
      { name: 'Jägermeister Shot', price: 0, description: 'Jägermeister served chilled for a bold herbal finish.' },
      { name: 'Tequila Shot', price: 2000, description: 'Classic tequila served as a crisp, fiery shot.' },
      { name: 'Jäger Bomb', price: 5000, description: 'Jägermeister paired with an energy drink for a bold, energetic combination.' },
    ],
  },
  {
    name: 'Cognac & Brandy',
    section: 'drinks',
    sortOrder: 6,
    items: [
      { name: 'Hennessy XO', price: 600000, description: 'Rich, complex and exceptionally smooth.' },
      { name: 'Hennessy VSOP', price: 200000, description: 'A well-rounded cognac with warm spice and fruity notes.' },
      { name: 'Hennessy VS', price: 150000, description: 'A bold and versatile cognac with a smooth, warming finish.' },
      { name: 'Rémy Martin XO', price: 500000, description: 'An elegant, rich and complex cognac designed for slow sipping.' },
      { name: 'Rémy Martin 1738', price: 200000, description: 'A refined cognac with rich fruit, spice and toasted oak notes.' },
      { name: 'Rémy Martin VSOP', price: 180000, description: 'Smooth and balanced with fruity, floral and subtle oak notes.' },
      { name: 'Martell Blue Swift', price: 200000, description: 'A distinctive cognac finished in bourbon barrels, offering a rich and contemporary character.' },
      { name: 'Martell VS', price: 150000, description: 'A smooth and vibrant cognac with fresh fruit and spice notes.' },
      { name: 'Martell XO', price: 600000, description: 'A luxurious, full-bodied cognac with deep fruit and spice character.' },
    ],
  },
  {
    name: 'Vodka',
    section: 'drinks',
    sortOrder: 7,
    items: [
      { name: 'Flymotion Vodka', price: 30000, description: 'A clean, versatile spirit suitable for cocktails, mixers or chilled service.' },
    ],
  },
  {
    name: 'Tequila',
    section: 'drinks',
    sortOrder: 8,
    items: [
      { name: '1800 Tequila Blanco', price: 170000, description: 'Crisp and vibrant with clean agave character.' },
      { name: '818 Tequila', price: 0, description: 'Smooth, approachable tequila with a refined agave profile.' },
      { name: 'Casamigos', price: 350000, description: 'A smooth tequila with soft agave, citrus and vanilla notes.' },
      { name: 'Salamanca Blanco', price: 245000, description: 'Fresh and vibrant blanco tequila with a clean finish.' },
      { name: 'Olmeca Tequila', price: 50000, description: 'A bold, approachable tequila with distinctive agave character.' },
    ],
  },
  {
    name: 'Gin',
    section: 'drinks',
    sortOrder: 9,
    items: [
      { name: "Hendrick's Gin", price: 100000, description: 'Distinctive gin with botanical character and subtle cucumber and rose notes.' },
      { name: "Gordon's Dry Gin", price: 0, description: 'A classic London Dry Gin with juniper-forward character and a crisp finish.' },
    ],
  },
  {
    name: 'Spirits',
    section: 'drinks',
    sortOrder: 10,
    items: [
      { name: 'Martell Blue Swift', price: 200000, description: 'Cognac with a modern character and rich bourbon-barrel influence.' },
      { name: 'Martell VS', price: 150000, description: 'A smooth, fruity and versatile cognac.' },
      { name: 'Observatory 20 Years', price: 110000, description: 'Aged spirit with a deeper, richer character and smooth finish.' },
      { name: 'Fire Water', price: 40000, description: 'A bold spirit with a warming, fiery character.' },
    ],
  },
  {
    name: 'Champagne & Sparkling',
    section: 'drinks',
    sortOrder: 11,
    items: [
      { name: 'Laurent-Perrier Brut', price: 0 },
      { name: 'Laurent-Perrier Rosé', price: 200000 },
      { name: 'Moët & Chandon Brut', price: 220000 },
      { name: 'Veuve Clicquot Brut', price: 250000 },
      { name: 'Moët & Chandon Rosé', price: 250000 },
      { name: 'Dom Pérignon', price: 500000 },
      { name: 'Canard-Duchêne Rosé', price: 140000 },
      { name: 'Canard-Duchêne Brut', price: 120000 },
      { name: 'Luc Belaire Rosé', price: 150000 },
      { name: 'Armand de Brignac — Ace of Spades', price: 0 },
      { name: 'Cristal', price: 0 },
      { name: 'Canard-Duchêne Demi-Sec', price: 100000 },
    ],
  },
  {
    name: 'Wines',
    section: 'drinks',
    sortOrder: 12,
    items: [
      { name: 'Bella Rosso — Sweet Red', price: 25000, description: 'A smooth, approachable sweet red wine with fruity character.' },
      { name: 'Sweet Kiss', price: 25000, description: 'A pleasantly sweet wine with a soft, fruity finish.' },
      { name: 'Lamothe Parrot', price: 25000, description: 'A balanced wine with an easy-drinking character.' },
      { name: 'Sandeman', price: 40000, description: 'A refined fortified wine with rich, distinctive flavour.' },
    ],
  },
  {
    name: 'Whisky & Whiskey',
    section: 'drinks',
    sortOrder: 13,
    items: [
      { name: 'Claymore', price: 30000, description: 'A smooth, approachable Scotch with gentle malt, oak and subtle smoky notes.' },
      { name: 'Monkey Shoulder', price: 80000, description: 'A rich and versatile blended malt with notes of vanilla, toasted oak and soft spice.' },
      { name: 'Observatory Whiskey — 20 Years', price: 110000, description: 'A beautifully aged whiskey with deep oak character, warm spice and a long, smooth finish.' },
      { name: 'The Macallan — 12 Years', price: 160000, description: 'Rich and elegant, with notes of dried fruit, soft spice, oak and a delicate sweetness.' },
      { name: 'The Macallan — 15 Years', price: 210000, description: 'A refined and complex expression offering rich dried fruit, warm spice and smooth oak.' },
      { name: 'The Macallan — Rare Cask', price: 650000, description: 'Exceptionally rich and layered, with notes of dried fruits, vanilla, spice and polished oak.' },
      { name: 'Glenfiddich — 15 Years', price: 160000, description: 'Smooth and beautifully balanced with ripe fruit, honey, warm spice and subtle oak.' },
      { name: 'Glenfiddich — 18 Years', price: 220000, description: 'Rich and sophisticated, offering baked fruit, oak, warm spice and a long, elegant finish.' },
      { name: 'Glenfiddich — 21 Years', price: 600000, description: 'An exceptionally refined whisky with rich fruit, vanilla, oak and delicate spice.' },
      { name: 'Glenfiddich — 23 Years', price: 800000, description: 'Deep, luxurious and complex, with layers of ripe fruit, oak, vanilla and gentle spice.' },
      { name: 'Glenmorangie — 10 Years', price: 110000, description: 'Light and elegant with bright citrus, vanilla and floral notes.' },
      { name: 'Glenmorangie — 12 Years', price: 140000, description: 'Smooth and aromatic, combining sweet fruit, vanilla and gentle oak.' },
      { name: 'Glenmorangie — 14 Years', price: 180000, description: 'Rich and expressive with ripe fruit, honey, spice and a beautifully smooth finish.' },
      { name: 'Glenmorangie — 18 Years', price: 260000, description: 'Luxuriously smooth with rich dried fruit, honey, vanilla and warm oak.' },
      { name: 'Teeling — Single Malt', price: 120000, description: 'A vibrant Irish single malt with layers of fruit, vanilla and gentle spice.' },
      { name: 'Teeling — 21 Years', price: 400000, description: 'An exceptional aged Irish whiskey with rich tropical fruit, oak and a long, elegant finish.' },
      { name: 'Jameson Black Barrel', price: 100000, description: 'Rich and smooth Irish whiskey with toasted oak, vanilla, caramel and subtle spice.' },
      { name: "Grant's Triple Wood", price: 40000, description: 'A smooth blended Scotch matured in three types of cask for layers of vanilla, fruit and oak.' },
      { name: "Grant's Triple Wood — 12 Years", price: 60000, description: 'Aged and refined, with mellow fruit, vanilla, oak and gentle spice.' },
      { name: 'Chivas Regal — 12 Years', price: 110000, description: 'Smooth and generous with notes of orchard fruit, honey, herbs and soft vanilla.' },
      { name: 'Chivas Regal — 15 Years', price: 140000, description: 'Rich and velvety with ripe fruit, caramel, vanilla and subtle spice.' },
      { name: 'Chivas Regal — 18 Years', price: 180000, description: 'Exceptionally smooth and complex, with dark chocolate, dried fruit, caramel and warm spice.' },
      { name: 'Fercullen Falls', price: 90000, description: 'A smooth Irish whiskey with delicate fruit, vanilla and gentle oak character.' },
      { name: 'Fire Water Cinnamon Whisky', price: 40000, description: "A bold cinnamon-infused whisky with a warm, fiery sweetness and a memorable spicy finish. \"You won't regret this taste.\"" },
    ],
  },
  {
    name: 'Beers & Lagers',
    section: 'drinks',
    sortOrder: 14,
    items: [
      { name: 'Tiger', price: 1500 },
      { name: 'Desperados', price: 1500 },
      { name: 'Budweiser', price: 2000 },
      { name: 'Star', price: 2000 },
      { name: 'Life', price: 2000 },
      { name: '33 Export', price: 2000 },
      { name: 'Smirnoff Ice', price: 1500 },
      { name: 'Star Radler', price: 1500 },
      { name: 'Orijin', price: 2000 },
      { name: 'Heineken', price: 2200 },
      { name: 'Flying Fish', price: 1500 },
      { name: 'Big Stout', price: 2500 },
      { name: 'Small Stout', price: 2000 },
      { name: 'Medium Stout', price: 0 },
      { name: 'Fearless', price: 0 },
      { name: 'Trophy', price: 2000 },
      { name: 'Trophy Stout', price: 2500 },
      { name: 'Hero', price: 2000 },
      { name: 'Legend Twist', price: 1500 },
      { name: 'Legend — Big', price: 2500 },
      { name: 'Gulder', price: 2000 },
      { name: 'Heineken — Medium', price: 2000 },
      { name: 'Extra Smooth Stout', price: 2000 },
      { name: 'Medium Legend', price: 1500 },
      { name: 'Smirnoff Double Black', price: 2000 },
    ],
  },
  {
    name: 'Soft Drinks',
    section: 'drinks',
    sortOrder: 15,
    items: [
      { name: 'Coke — Can', price: 1500 },
      { name: 'Sprite — Can', price: 1500 },
      { name: 'Fayrouz', price: 1500 },
      { name: 'Maltina', price: 1500 },
      { name: 'Schweppes Tonic Water', price: 1000 },
      { name: 'Amstel Malta', price: 1500 },
      { name: 'Cranberry Juice', price: 9000 },
      { name: 'Climax', price: 3000 },
    ],
  },
  {
    name: 'Energy Drinks',
    section: 'drinks',
    sortOrder: 16,
    items: [
      { name: 'Red Bull', price: 3000 },
      { name: 'Black Bullet', price: 4000 },
    ],
  },
  {
    name: 'Irish Cream',
    section: 'drinks',
    sortOrder: 17,
    items: [{ name: 'Baileys', price: 40000 }],
  },
  {
    name: 'Herbal Liqueur',
    section: 'drinks',
    sortOrder: 18,
    items: [
      { name: 'Master Jagermeister', price: 40000 },
      { name: 'Orijin Bitters', price: 3000 },
    ],
  },
  {
    name: 'Cigarettes & Shisha',
    section: 'drinks',
    sortOrder: 19,
    items: [
      { name: 'Shisha', price: 10000 },
      { name: 'Special Shisha', price: 12000 },
      { name: 'Cigarette', price: 2000 },
      { name: 'Benson Filter', price: 2000 },
      { name: 'Benson Switch', price: 2000 },
      { name: 'Dunhill Switch', price: 2000 },
      { name: 'Shisha Coal', price: 1000 },
    ],
  },
];
